### ISSUE TITLE
Az2-notoco

### ISSUE THREAD

**Issue by timtumturutumtum** [notoco/univ#2]
Kontynuując temat rozpoczęty u mbebe, zaistalowane script.skinshortcuts w wersji 1.19 alpha, zastanawiam się czy to wina coreelec.
Wrzucę wersje 1.20 i zobaczę czy coś się poprawi.

Skina będziesz updatował?
Może jakiś konkretny changelog?

**Comment by notoco** [comment]
Też używam coreelec. Skina będę updatował, ale changeloga nie będzie. Śledź commity. Robię to tylko pod siebie. Jak coś mi nie pasuje, to zmieniam. Aktualizacje mogą wysyłać system, wtedy zmiana skórki przez SSH pomaga.

**Comment by notoco** [comment]
U mnie na czystym coreelec 9.2 z moim repo, z repo KWP, ptw collection wszystko działa.

**Comment by notoco** [comment]
I jeszcze. Poprawki czasem są b. drobne. Niby wszystko jest ok, a na komputerze u dzieci coś źle wygląda to poprawiam 1 linijkę i leci nowa wersja...

**Comment by timtumturutumtum** [comment]
Czysty profil na coreele
Dodane tylko Twoje repozytorium.
Instalacja skórki, odpalenie i...

~~2019-11-10 00:00:54.373 T:4091662352  NOTICE:   load skin from: /storage/.kodi/addons/skin.arctic.zephyr.2-notoco (version: 20191108.4)
2019-11-10 00:00:55.416 T:4091662352   ERROR: unmatched parentheses in container.content(episodes
2019-11-10 00:00:58.146 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-submenu-1
2019-11-10 00:00:58.149 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-template-global
2019-11-10 00:00:58.156 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-mainmenu
2019-11-10 00:00:58.157 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-submenu
2019-11-10 00:00:58.162 T:4091662352 WARNING: Previous line repeats 1 times.
2019-11-10 00:00:58.162 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-template-spotlight-mainmenu
2019-11-10 00:00:58.162 T:4091662352 WARNING: Skin has invalid include: skinshortcuts-template-spotlight-submenu
2019-11-10 00:00:58.237 T:3761140608   ERROR: GetDirectory - Error getting include
2019-11-10 00:00:58.269 T:4091662352   ERROR: Previous line repeats 2 times.
2019-11-10 00:00:58.269 T:4091662352   ERROR: Control 301 in window 10000 has been asked to focus, but it can't
2019-11-10 00:01:02.262 T:3643274112   ERROR: Traceback (most recent call last):
2019-11-10 00:01:02.263 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 97, in buildMenu
2019-11-10 00:01:02.264 T:3643274112   ERROR:     self.writexml( profilelist, mainmenuID, groups, numLevels, buildMode, progress, options, minitems )
2019-11-10 00:01:02.264 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 504, in writexml
2019-11-10 00:01:02.264 T:3643274112   ERROR:     submenudata = DATA._get_shortcuts( submenu, submenuDefaultID, True, profile[0] )
2019-11-10 00:01:02.264 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 156, in _get_shortcuts
2019-11-10 00:01:02.266 T:3643274112   ERROR:     tree = xmltree.parse( path )
2019-11-10 00:01:02.266 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
2019-11-10 00:01:02.266 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
2019-11-10 00:01:02.266 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
2019-11-10 00:01:02.267 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
2019-11-10 00:01:02.267 T:3643274112   ERROR: ParseError: mismatched tag: line 82, column 2
2019-11-10 00:01:02.334 T:3643274112   ERROR: GetDirectory - Error getting /storage/.kodi/media/Fonts/
2019-11-10 00:01:02.334 T:3643274112   ERROR: GetDirectory - Error getting special://home/media/Fonts/
2019-11-10 00:01:02.420 T:3643274112  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
2019-11-10 00:01:02.420 T:3643274112  NOTICE: Enabled debug logging due to GUI setting. Level 2.
2019-11-10 00:01:02.422 T:3643274112   DEBUG: CAddonSettings[script.skinshortcuts]: loading setting definitions
2019-11-10 00:01:02.422 T:3643274112   DEBUG: CAddonSettings[script.skinshortcuts]: trying to load setting definitions from old format...
2019-11-10 00:01:02.423 T:3643274112   DEBUG: CAddonSettings[script.skinshortcuts]: loading setting values
2019-11-10 00:01:02.427 T:3643274112   DEBUG: script.skinshortcuts: Profile found: Master user (special://masterprofile/)
2019-11-10 00:01:02.428 T:4091662352   DEBUG: ------ Window Init () ------
2019-11-10 00:01:02.445 T:3643274112   DEBUG: script.skinshortcuts: Includes file does not exist
2019-11-10 00:01:02.458 T:3684680576   DEBUG: Thread Timer start, auto delete: false
2019-11-10 00:01:02.470 T:4091662352   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
2019-11-10 00:01:02.528 T:3643274112   DEBUG: script.skinshortcuts: Building menu for profile Master user
2019-11-10 00:01:02.534 T:3684680576   DEBUG: Thread Timer 3684680576 terminating
2019-11-10 00:01:02.534 T:3693073280   DEBUG: Thread Timer start, auto delete: false
2019-11-10 00:01:03.040 T:3693073280   DEBUG: Thread Timer 3693073280 terminating
2019-11-10 00:01:03.597 T:4091662352   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2019-11-10 00:01:04.155 T:3643274112   DEBUG: script.skinshortcuts: Failed to write menu
2019-11-10 00:01:04.155 T:3643274112   ERROR: Traceback (most recent call last):
2019-11-10 00:01:04.155 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 97, in buildMenu
2019-11-10 00:01:04.156 T:3643274112   ERROR:     self.writexml( profilelist, mainmenuID, groups, numLevels, buildMode, progress, options, minitems )
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/xmlfunctions.py", line 504, in writexml
2019-11-10 00:01:04.156 T:3643274112   ERROR:     submenudata = DATA._get_shortcuts( submenu, submenuDefaultID, True, profile[0] )
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/storage/.kodi/addons/script.skinshortcuts/resources/lib/datafunctions.py", line 156, in _get_shortcuts
2019-11-10 00:01:04.156 T:3643274112   ERROR:     tree = xmltree.parse( path )
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
2019-11-10 00:01:04.156 T:3643274112   ERROR:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
2019-11-10 00:01:04.157 T:3643274112   ERROR: ParseError: mismatched tag: line 82, column 2
2019-11-10 00:01:04.157 T:3643274112  NOTICE: Disabled debug logging due to GUI setting. Level 0.
2019-11-10 00:01:04.157 T:3643274112  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
2019-11-10 00:01:40.725 T:4091662352  NOTICE: Quitting due to POSIX signal
2019-11-10 00:01:40.742 T:4091662352  NOTICE: Stopping player
2019-11-10 00:01:40.742 T:4091662352  NOTICE: Storing total System Uptime
2019-11-10 00:01:40.743 T:4091662352  NOTICE: Saving settings
2019-11-10 00:01:40.767 T:4091662352  NOTICE: Saving skin settings
2019-11-10 00:01:40.776 T:4091662352  NOTICE: Stopping all
2019-11-10 00:01:40.776 T:4091662352  NOTICE: ES: Stopping event server
2019-11-10 00:01:41.346 T:3869217664  NOTICE: ES: UDP Event server stopped
2019-11-10 00:01:41.723 T:4091662352  NOTICE: stopping zeroconf publishing
2019-11-10 00:01:41.765 T:4091662352  NOTICE: CWebServer[8080]: Stopped
2019-11-10 00:01:41.766 T:4091662352  NOTICE: stop dvd detect media
2019-11-10 00:01:41.965 T:4091662352  NOTICE: Application stopped
2019-11-10 00:01:42.166 T:4091662352  NOTICE: XBApplicationEx: destroying...
2019-11-10 00:01:44.603 T:4091662352  NOTICE: unload skin
2019-11-10 00:01:44.747 T:4091662352  NOTICE: unload sections
2019-11-10 00:01:45.511 T:4091662352  NOTICE: XBApplicationEx: application stopped!CoreELEC:~ #~~

**Comment by notoco** [comment]
Ok - poprawione w wersji 20191110
Przy dodawaniu własnych wyszukiwarek wkradł się jakiś błąd - przywróciłem domyślne.
